"""Data types for ED-318"""

# This file is autogenerated; do not modify manually!

from __future__ import annotations

from enum import Enum
from typing import Dict, List, Optional

from uas_standards import Operation

from implicitdict import ImplicitDict, StringBasedDateTime




class FeatureCollectionType(str, Enum):
    FeatureCollection = "FeatureCollection"


Geometry = str
"""Any one of the GeoJSON geometry types, including LayeredGeoJSON validation."""


class UASZoneExtendedProperties(ImplicitDict):
    pass


NormalGeometry = str


class GeometryCollectionType(str, Enum):
    GeometryCollection = "GeometryCollection"


class GeometryCollectionLayerUom(str, Enum):
    """The unit of measurement in which the upper and lower values are expressed. Allowable values:
    m = metres
    ft = feet
    If this member is not specified, the units should be assumed to be metres.
    """

    m = "m"
    ft = "ft"


class ZoneType(str, Enum):
    USPACE = "USPACE"
    PROHIBITED = "PROHIBITED"
    REQ_AUTHORIZATION = "REQ_AUTHORIZATION"
    CONDITIONAL = "CONDITIONAL"
    NO_RESTRICTION = "NO_RESTRICTION"


class ZoneVariant(str, Enum):
    COMMON = "COMMON"
    CUSTOMIZED = "CUSTOMIZED"


ZoneReason = List[str]


class WeekDayType(str, Enum):
    MON = "MON"
    TUE = "TUE"
    WED = "WED"
    THU = "THU"
    FRI = "FRI"
    SAT = "SAT"
    SUN = "SUN"
    ANY = "ANY"


class DaylightEventType(str, Enum):
    BMCT = "BMCT"
    SR = "SR"
    SS = "SS"
    EECT = "EECT"


class AuthorityRole(str, Enum):
    AUTHORIZATION = "AUTHORIZATION"
    NOTIFICATION = "NOTIFICATION"
    INFORMATION = "INFORMATION"


class YesNoType(str, Enum):
    YES = "YES"
    NO = "NO"


class TextShortType(ImplicitDict):
    text: Optional[str]

    lang: str


class TextLongType(ImplicitDict):
    text: Optional[str]

    lang: str


URNType = str


class DailyPeriod(ImplicitDict):
    day: List[WeekDayType]

    startTime: Optional[str]

    startEvent: Optional[DaylightEventType]

    endTime: Optional[str]

    endEvent: Optional[DaylightEventType]


class VerticalReference(str, Enum):
    """A code indicating a vertical reference system. Allowed values:
    AGL = Above ground level (or above water surface, as applicable)
    AMSL = Above Mean Sea Level
    WGS84 = Above the surface of the WGS-84 ellipsoid (Ellipsoidal height)
    """

    AGL = "AGL"
    AMSL = "AMSL"
    WGS84 = "WGS84"


class FeatureType(str, Enum):
    Feature = "Feature"


class Feature(ImplicitDict):
    """GeoJSON Feature"""

    type: FeatureType = FeatureType.Feature

    id: Optional[str]

    properties: str

    geometry: str

    bbox: Optional[List[float]]


class PointType(str, Enum):
    Point = "Point"


class PointLayerUom(str, Enum):
    """The unit of measurement in which the upper and lower values are expressed. Allowable values:
    m = metres
    ft = feet
    If this member is not specified, the units should be assumed to be metres.
    """

    m = "m"
    ft = "ft"


class PointLayer(ImplicitDict):
    upper: Optional[float]
    """The value of the upper limit of the airspace layer expressed in metres (m) or feet (ft), in relation with the vertical datum specified in the upperReference property. A positive value is interpreted as meaning "above" the reference surface."""

    upperReference: Optional[VerticalReference]

    lower: Optional[float]
    """The value of the lower limit of the airspace layer expressed in metres (m) or feet (ft), in relation with the vertical datum specified in the lowerReference property. A positive value is interpreted as meaning "above" the reference surface."""

    lowerReference: Optional[VerticalReference]

    uom: Optional[PointLayerUom] = "m"
    """The unit of measurement in which the upper and lower values are expressed. Allowable values:
    m = metres
    ft = feet
    If this member is not specified, the units should be assumed to be metres.
    """


class Point(ImplicitDict):
    """GeoJSON Point with LayeredGeoJSON extent validation"""

    type: PointType = PointType.Point

    coordinates: List[float]

    bbox: Optional[List[float]]

    layer: Optional[PointLayer]


class LineStringType(str, Enum):
    LineString = "LineString"


LineStringCoordinatesItem = List[float]


class LineStringLayerUom(str, Enum):
    """The unit of measurement in which the upper and lower values are expressed. Allowable values:
    m = metres
    ft = feet
    If this member is not specified, the units should be assumed to be metres.
    """

    m = "m"
    ft = "ft"


class LineStringLayer(ImplicitDict):
    upper: Optional[float]
    """The value of the upper limit of the airspace layer expressed in metres (m) or feet (ft), in relation with the vertical datum specified in the upperReference property. A positive value is interpreted as meaning "above" the reference surface."""

    upperReference: Optional[VerticalReference]

    lower: Optional[float]
    """The value of the lower limit of the airspace layer expressed in metres (m) or feet (ft), in relation with the vertical datum specified in the lowerReference property. A positive value is interpreted as meaning "above" the reference surface."""

    lowerReference: Optional[VerticalReference]

    uom: Optional[LineStringLayerUom] = "m"
    """The unit of measurement in which the upper and lower values are expressed. Allowable values:
    m = metres
    ft = feet
    If this member is not specified, the units should be assumed to be metres.
    """


class LineString(ImplicitDict):
    """GeoJSON LineString"""

    type: LineStringType = LineStringType.LineString

    coordinates: List[LineStringCoordinatesItem]

    bbox: Optional[List[float]]

    layer: Optional[LineStringLayer]


class PolygonType(str, Enum):
    Polygon = "Polygon"


PolygonCoordinatesItemItem = List[float]


PolygonCoordinatesItem = List[PolygonCoordinatesItemItem]


class PolygonLayerUom(str, Enum):
    """The unit of measurement in which the upper and lower values are expressed. Allowable values:
    m = metres
    ft = feet
    If this member is not specified, the units should be assumed to be metres.
    """

    m = "m"
    ft = "ft"


class PolygonLayer(ImplicitDict):
    upper: Optional[float]
    """The value of the upper limit of the airspace layer expressed in metres (m) or feet (ft), in relation with the vertical datum specified in the upperReference property. A positive value is interpreted as meaning "above" the reference surface."""

    upperReference: Optional[VerticalReference]

    lower: Optional[float]
    """The value of the lower limit of the airspace layer expressed in metres (m) or feet (ft), in relation with the vertical datum specified in the lowerReference property. A positive value is interpreted as meaning "above" the reference surface."""

    lowerReference: Optional[VerticalReference]

    uom: Optional[PolygonLayerUom] = "m"
    """The unit of measurement in which the upper and lower values are expressed. Allowable values:
    m = metres
    ft = feet
    If this member is not specified, the units should be assumed to be metres.
    """


class Polygon(ImplicitDict):
    """GeoJSON Polygon"""

    type: PolygonType = PolygonType.Polygon

    coordinates: List[PolygonCoordinatesItem]

    bbox: Optional[List[float]]

    layer: Optional[PolygonLayer]


class MultiPointType(str, Enum):
    MultiPoint = "MultiPoint"


MultiPointCoordinatesItem = List[float]


class MultiPointLayerUom(str, Enum):
    """The unit of measurement in which the upper and lower values are expressed. Allowable values:
    m = metres
    ft = feet
    If this member is not specified, the units should be assumed to be metres.
    """

    m = "m"
    ft = "ft"


class MultiPointLayer(ImplicitDict):
    upper: Optional[float]
    """The value of the upper limit of the airspace layer expressed in metres (m) or feet (ft), in relation with the vertical datum specified in the upperReference property. A positive value is interpreted as meaning "above" the reference surface."""

    upperReference: Optional[VerticalReference]

    lower: Optional[float]
    """The value of the lower limit of the airspace layer expressed in metres (m) or feet (ft), in relation with the vertical datum specified in the lowerReference property. A positive value is interpreted as meaning "above" the reference surface."""

    lowerReference: Optional[VerticalReference]

    uom: Optional[MultiPointLayerUom] = "m"
    """The unit of measurement in which the upper and lower values are expressed. Allowable values:
    m = metres
    ft = feet
    If this member is not specified, the units should be assumed to be metres.
    """


class MultiPoint(ImplicitDict):
    """GeoJSON MultiPoint"""

    type: MultiPointType = MultiPointType.MultiPoint

    coordinates: List[MultiPointCoordinatesItem]

    bbox: Optional[List[float]]

    layer: Optional[MultiPointLayer]


class MultiLineStringType(str, Enum):
    MultiLineString = "MultiLineString"


MultiLineStringCoordinatesItemItem = List[float]


MultiLineStringCoordinatesItem = List[MultiLineStringCoordinatesItemItem]


class MultiLineStringLayerUom(str, Enum):
    """The unit of measurement in which the upper and lower values are expressed. Allowable values:
    m = metres
    ft = feet
    If this member is not specified, the units should be assumed to be metres.
    """

    m = "m"
    ft = "ft"


class MultiLineStringLayer(ImplicitDict):
    upper: Optional[float]
    """The value of the upper limit of the airspace layer expressed in metres (m) or feet (ft), in relation with the vertical datum specified in the upperReference property. A positive value is interpreted as meaning "above" the reference surface."""

    upperReference: Optional[VerticalReference]

    lower: Optional[float]
    """The value of the lower limit of the airspace layer expressed in metres (m) or feet (ft), in relation with the vertical datum specified in the lowerReference property. A positive value is interpreted as meaning "above" the reference surface."""

    lowerReference: Optional[VerticalReference]

    uom: Optional[MultiLineStringLayerUom] = "m"
    """The unit of measurement in which the upper and lower values are expressed. Allowable values:
    m = metres
    ft = feet
    If this member is not specified, the units should be assumed to be metres.
    """


class MultiLineString(ImplicitDict):
    """GeoJSON MultiLineString"""

    type: MultiLineStringType = MultiLineStringType.MultiLineString

    coordinates: List[MultiLineStringCoordinatesItem]

    bbox: Optional[List[float]]

    layer: Optional[MultiLineStringLayer]


class MultiPolygonType(str, Enum):
    MultiPolygon = "MultiPolygon"


MultiPolygonCoordinatesItemItemItem = List[float]


MultiPolygonCoordinatesItemItem = List[MultiPolygonCoordinatesItemItemItem]


MultiPolygonCoordinatesItem = List[MultiPolygonCoordinatesItemItem]


class MultiPolygonLayerUom(str, Enum):
    """The unit of measurement in which the upper and lower values are expressed. Allowable values:
    m = metres
    ft = feet
    If this member is not specified, the units should be assumed to be metres.
    """

    m = "m"
    ft = "ft"


class MultiPolygonLayer(ImplicitDict):
    upper: Optional[float]
    """The value of the upper limit of the airspace layer expressed in metres (m) or feet (ft), in relation with the vertical datum specified in the upperReference property. A positive value is interpreted as meaning "above" the reference surface."""

    upperReference: Optional[VerticalReference]

    lower: Optional[float]
    """The value of the lower limit of the airspace layer expressed in metres (m) or feet (ft), in relation with the vertical datum specified in the lowerReference property. A positive value is interpreted as meaning "above" the reference surface."""

    lowerReference: Optional[VerticalReference]

    uom: Optional[MultiPolygonLayerUom] = "m"
    """The unit of measurement in which the upper and lower values are expressed. Allowable values:
    m = metres
    ft = feet
    If this member is not specified, the units should be assumed to be metres.
    """


class MultiPolygon(ImplicitDict):
    """GeoJSON MultiPolygon"""

    type: MultiPolygonType = MultiPolygonType.MultiPolygon

    coordinates: List[MultiPolygonCoordinatesItem]

    bbox: Optional[List[float]]

    layer: Optional[MultiPolygonLayer]


class DatasetMetadata(ImplicitDict):
    """collection metadata"""

    validFrom: Optional[StringBasedDateTime]

    validTo: Optional[StringBasedDateTime]

    issued: Optional[StringBasedDateTime]

    provider: Optional[List[TextShortType]]

    description: Optional[List[TextShortType]]

    otherGeoid: Optional[URNType]

    technicalLimitations: Optional[List[TextShortType]]


class Authority(ImplicitDict):
    """authority"""

    name: Optional[List[TextShortType]]

    service: Optional[List[TextShortType]]

    contactName: Optional[List[TextShortType]]

    siteURL: Optional[str]

    email: Optional[str]

    phone: Optional[str]

    purpose: AuthorityRole

    intervalBefore: Optional[str]
    """A period of time expressed according to the ISO 8601 rules for time intervals."""


class TimePeriod(ImplicitDict):
    """timePeriod"""

    startDateTime: Optional[StringBasedDateTime]

    endDateTime: Optional[StringBasedDateTime]

    schedule: Optional[List[DailyPeriod]]


class GeometryCollectionLayer(ImplicitDict):
    upper: Optional[float]
    """The value of the upper limit of the airspace layer expressed in metres (m) or feet (ft), in relation with the vertical datum specified in the upperReference property. A positive value is interpreted as meaning "above" the reference surface."""

    upperReference: Optional[VerticalReference]

    lower: Optional[float]
    """The value of the lower limit of the airspace layer expressed in metres (m) or feet (ft), in relation with the vertical datum specified in the lowerReference property. A positive value is interpreted as meaning "above" the reference surface."""

    lowerReference: Optional[VerticalReference]

    uom: Optional[GeometryCollectionLayerUom] = "m"
    """The unit of measurement in which the upper and lower values are expressed. Allowable values:
    m = metres
    ft = feet
    If this member is not specified, the units should be assumed to be metres.
    """


class GeometryCollection(ImplicitDict):
    """GeoJSON GeometryCollection"""

    type: GeometryCollectionType = GeometryCollectionType.GeometryCollection

    geometries: List[NormalGeometry]

    bbox: Optional[List[float]]

    layer: Optional[GeometryCollectionLayer]


class FeatureCollection(ImplicitDict):
    """GeoJSON FeatureCollection"""

    type: FeatureCollectionType = FeatureCollectionType.FeatureCollection

    name: Optional[str]

    bbox: Optional[List[float]]

    metadata: Optional[DatasetMetadata]

    features: List[Feature]


class UASZone(ImplicitDict):
    """UASZoneVersion"""

    identifier: str

    country: str

    name: Optional[List[TextShortType]]

    type: ZoneType

    variant: ZoneVariant

    restrictionConditions: Optional[str]

    region: Optional[int]

    reason: Optional[ZoneReason]

    otherReasonInfo: Optional[List[TextShortType]]

    regulationExemption: Optional[YesNoType]

    message: Optional[List[TextShortType]]

    zoneAuthority: List[Authority]

    limitedApplicability: Optional[List[TimePeriod]]

    extendedProperties: Optional[UASZoneExtendedProperties]

